---
title: "Assignment 1: Introduction"
author: "Yixin Fang"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assigment section on Sakai.


## 1) Finish setting up R Studio

### Install TinyTex
Now, run this code cell the same way. This will install "tinytex" -- a helper app that allows you to knit your markdown documents into professional quality PDFs.
```{r install tiny tex, eval=FALSE, include=FALSE}
#install tinytext
tinytex::install_tinytex()
```

### Set your default knit directory
This setting will help deal with relative paths later on...
 - From the Tool menu, select `Global Options`
 - Select the RMarkdown section
 - In the "Evaluate chunks in directory", set the option to "Project"


## 2) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: 
I do not have any formal training of R, but some of my courses and also my MP require the use of it, so I was learning on the job. I also took some workshops provided by the program and online courses about the basics of R. I have only heard of Git/GitHub but never used it. 

2. Are there any components of the course about which you feel confident?

> Answer:
I have heard of some of the topics that will be covered in this class and know some basic functions related to the topics. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: 
I have never dealt with some contents such as time series data and spatial data in R, and I'm not sure how deep we will go into each topic. GitHub is also new for me, but I'm glad we can cover this in class and definitely hope to learn more about it.


## 3) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: 

## 4) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Sakai. 
